version: '3.4'

services:
  netcoreidentityapp:
    image: ${DOCKER_REGISTRY-}netcoreidentityapp
    build:
      context: .
      dockerfile: NetCoreIdentityApp/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8000:80
    networks:
      - api-network
    depends_on:
      - mssql
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
      ACCEPT_EULA: "Y"
    # MSSQL_PID: Developer
      SA_PASSWORD: Secret1234..
    ports: 
    # host-port:container-port
      -  1433:1433
    volumes:
      - /var/opt/mssql/data/
    networks:
      - api-network
    restart: always
networks:
  api-network:
    driver: bridge
